name: whatsappclone
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.0.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  # A Flutter package to use fonts from fonts.google.com.
  google_fonts: ^6.2.1
  # Draw SVG files
  flutter_svg: ^2.0.10+1
  flutter_easyloading: ^3.0.5
  flutter_screenutil: ^5.9.3
#  open_settings: ^2.0.2

  pin_code_fields: ^8.0.0
  # dio: ^5.0.0
  http: ^1.0.0
  # path: ^1.8.3
  # path_provider: ^2.1.1
  # http_parser: ^4.0.2
  open_settings_plus: ^0.4.0
  # loading_indicator: ^3.1.0
  flutter_secure_storage: ^9.2.4
  logger: ^2.5.0
  connectivity_plus: ^6.1.4

  # For image
  image_picker: ^1.1.2
  image_cropper: ^9.0.0
  flutter_image_compress: ^2.4.0
  cached_network_image: ^3.4.1

  # notification
  firebase_core: ^3.13.1
  firebase_messaging: ^15.2.6
  flutter_local_notifications: ^19.2.1

  # mobile_scanner: ^3.2.0
  mobile_scanner:
  url_launcher: ^6.2.5

  video_player: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/icons/nav/

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png

